version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - USER_SERVICE_HOST=user-service # Nama service di Docker Compose
      - APP_SERVICE_HOST=app-service
    networks:
      - microservices-network
    depends_on:
      - user-service
      - app-service

  user-service:
    image: your-username/user-service:latest
    container_name: user-service
    networks:
      - microservices-network
    # Port tidak perlu diexpose ke host (internal only)
    expose:
      - "8001"

  app-service:
    image: your-username/app-service:latest
    container_name: app-service
    networks:
      - microservices-network
    expose:
      - "8002"

networks:
  microservices-network:
    driver: bridge
